import { useMemo, useState } from 'react';
import {
  Bell, Building2, CalendarDays, Car, FileText, Home, MapPin, MessageCircle,
  Paperclip, Plus, Search, Send, Settings, ShieldCheck, Sparkles, Users, Wrench, X
} from 'lucide-react';
import { jobs, type Job, type Stage } from './demo';
import { applyPalette, paletteFromLogo } from './lib';
import { Brand, CarArt, Status, stageLabels, type AppView } from './components';

function Shell({children,title,mode,active,onHome}:{children:React.ReactNode;title:string;mode:string;active:string;onHome:()=>void}){
  const items=[['Übersicht',Home],['Werkstatt',Wrench],['Termine',CalendarDays],['Kunden',Users],['Fahrzeuge',Car],['Dokumente',FileText]] as const;
  return <div className="app-shell"><aside className="sidebar"><button className="side-brand" onClick={onHome}><Brand compact/></button><nav>{items.map(([name,Icon])=><button key={name} className={active===name?'active':''}><Icon size={18}/><span>{name}</span></button>)}</nav><div className="side-bottom"><button><Settings size={18}/><span>Einstellungen</span></button><button className="profile"><span>PW</span><div><b>{title}</b><small>{mode}</small></div></button></div></aside><main className="app-main"><div className="app-top"><div className="app-search"><Search size={17}/><span>Fahrzeug, Kunde oder Auftrag suchen …</span></div><button className="icon-button"><Bell size={18}/><i/></button><div className="top-identity"><span>CS</span><div><b>{title}</b><small>{mode}</small></div></div></div>{children}</main></div>;
}

function PageHead({title,subtitle,children}:{title:string;subtitle:string;children?:React.ReactNode}){return <div className="page-head"><div><h1>{title}</h1><p>{subtitle}</p></div>{children}</div>}

const orderStages:Stage[]=['arrived','diagnosis','approval','repair','pickup'];
function JobCard({job}:{job:Job}){return <article className="job-card"><div className="job-car"><CarArt tone={Number(job.id)%5}/><div><b>{job.vehicle}</b><small>{job.plate}{job.mileage?` · ${job.mileage.toLocaleString('de-DE')} km`:''}</small></div></div><p>{job.complaint}</p><footer><span>#{job.id}</span><Status stage={job.stage}/></footer></article>}

function DemoChat({open,onClose,audience}:{open:boolean;onClose:()=>void;audience:'customer'|'workshop'}){
  const [messages,setMessages]=useState([
    {mine:false,text:'Wir haben die Diagnose abgeschlossen. Die Lambdasonde vor Kat liefert unplausible Werte.',time:'09:18'},
    {mine:true,text:'Ist das Fahrzeug bis zur Reparatur noch fahrbar?',time:'09:21'},
    {mine:false,text:'Für kurze Strecken ja. Der Kostenvoranschlag liegt bereits im Auftrag.',time:'09:24'}
  ]);
  const [text,setText]=useState('');
  if(!open)return null;
  const send=()=>{if(!text.trim())return;setMessages(v=>[...v,{mine:true,text:text.trim(),time:new Date().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}]);setText('')};
  return <div className="drawer-backdrop" onMouseDown={onClose}><aside className="chat-drawer" onMouseDown={e=>e.stopPropagation()}><header><div><span className="chat-vehicle"><Car size={17}/></span><div><b>BMW X3 3.0i</b><small>SAD XX 123 · Auftrag #184</small></div></div><button onClick={onClose}><X/></button></header><div className="chat-note"><ShieldCheck size={14}/> Chat und formelle Reparaturfreigabe sind bewusst getrennt.</div><div className="messages">{messages.map((m,i)=><div key={i} className={`message ${m.mine?'mine':''}`}><p>{m.text}</p><small>{m.mine?(audience==='customer'?'Du':'Werkstatt'):(audience==='customer'?'Werkstatt':'Kunde')} · {m.time}</small></div>)}</div><footer><button className="attach" title="Datei anhängen"><Paperclip/></button><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')send()}} placeholder="Nachricht zum Fahrzeug …"/><button className="send" onClick={send}><Send/></button></footer></aside></div>;
}

export function OfficeDashboard({setView}:{setView:(v:AppView)=>void}){
 const [chat,setChat]=useState(false); const [selected,setSelected]=useState<Job>(jobs[0]);
 const counts=useMemo(()=>Object.fromEntries(orderStages.map(s=>[s,jobs.filter(j=>j.stage===s).length])),[]);
 return <Shell onHome={()=>setView('home')} title="Carplus Service" mode="Büro" active="Übersicht"><div className="page"><PageHead title="Werkstattübersicht" subtitle="Was heute Aufmerksamkeit braucht – ohne Informationssuche."><div className="head-actions"><span className="realtime"><i/> Echtzeit verbunden</span><button className="btn primary"><Plus size={16}/> Neue Annahme</button></div></PageHead><div className="metrics"><article><small>HEUTE</small><b>8</b><span>Termine</span></article><article><small>NEUE ANFRAGEN</small><b>3</b><span>prüfen</span></article><article><small>FREIGABEN</small><b>2</b><span>offen</span></article><article><small>ABHOLBEREIT</small><b>1</b><span>Fahrzeug</span></article></div><div className="board">{orderStages.map(stage=><section key={stage}><header><span>{stageLabels[stage]}</span><b>{counts[stage]}</b></header><div>{jobs.filter(j=>j.stage===stage).map(j=><button className="card-button" onClick={()=>setSelected(j)} key={j.id}><JobCard job={j}/></button>)}</div></section>)}</div><div className="lower-grid"><section className="panel focus-card"><div><span className="overline">AUSGEWÄHLTER VORGANG</span><h3>{selected.vehicle}</h3><small>{selected.plate} · Auftrag #{selected.id}</small></div><div className="focus-action"><Status stage={selected.stage}/><button className="btn secondary" onClick={()=>setChat(true)}><MessageCircle size={16}/> Fahrzeugchat</button><button className="btn primary">Vorgang öffnen</button></div></section><section className="panel incoming"><div><span className="overline">NEUE KUNDENANFRAGE</span><h3>Anna Meier</h3><p>möchte Kunde bei Carplus Service Center werden.</p></div><div><button className="btn secondary">Ablehnen</button><button className="btn primary">Annehmen</button></div></section></div></div><DemoChat open={chat} onClose={()=>setChat(false)} audience="workshop"/></Shell>;
}

export function WorkshopBoard({setView}:{setView:(v:AppView)=>void}){
 const queue=jobs.filter(j=>j.stage==='arrived'||j.stage==='repair'); const [claimed,setClaimed]=useState<string[]>([]); const [selected,setSelected]=useState<Job>(queue[0]); const [chat,setChat]=useState(false);
 const take=(job:Job)=>{setSelected(job);setClaimed(v=>v.includes(job.id)?v:[...v,job.id])};
 return <Shell onHome={()=>setView('home')} title="Carplus Service" mode="Werkstatt" active="Werkstatt"><div className="page workshop-page"><PageHead title="Werkstattboard" subtitle="Nächsten Auftrag nehmen. Arbeiten. Ergebnis eintragen."><span className="realtime"><i/> Live mit dem Büro</span></PageHead><div className="workshop-grid"><section className="panel queue"><div className="panel-title"><div><span className="overline">OFFENE ARBEITEN</span><h3>{queue.length} Fahrzeuge warten</h3></div><b>{queue.length}</b></div>{queue.map((job,i)=><article key={job.id} className={selected.id===job.id?'selected':''} onClick={()=>setSelected(job)}><span className={`queue-index ${job.stage==='repair'?'repair':''}`}>{job.stage==='repair'?'R':i+1}</span><div className="queue-copy"><b>{job.vehicle}</b><small>{job.plate}</small><p>{job.stage==='repair'?'Reparatur vom Kunden freigegeben':job.complaint}</p></div><button className={`btn ${claimed.includes(job.id)?'muted':'primary'}`} disabled={claimed.includes(job.id)} onClick={e=>{e.stopPropagation();take(job)}}>{claimed.includes(job.id)?'Übernommen':job.stage==='repair'?'Reparatur nehmen':'Diagnose nehmen'}</button></article>)}</section><section className="panel work-card"><span className="overline">WERKSTATTKARTE</span><div className="work-car"><CarArt large tone={0}/><div><h2>{selected.vehicle}</h2><span className="plate">{selected.plate}</span></div></div><div className="complaint"><small>KUNDENBEANSTANDUNG</small><p>{selected.complaint}</p></div><div className="work-buttons"><button className="btn primary xl full">{selected.stage==='repair'?'Reparatur öffnen':'Diagnose eintragen'}</button>{claimed.includes(selected.id)&&<button className="btn secondary full" onClick={()=>setChat(true)}><MessageCircle size={17}/> Fahrzeugchat</button>}</div><p className="permission-note">Der Chat erscheint dem Mechaniker nur bei übernommenem Auftrag oder ausdrücklicher Berechtigung.</p></section></div></div><DemoChat open={chat} onClose={()=>setChat(false)} audience="workshop"/></Shell>;
}

function VehicleCard({name,plate,detail,active,tone}:{name:string;plate:string;detail:string;active?:boolean;tone:number}){return <article className="panel vehicle-card"><CarArt large tone={tone}/><div className="vehicle-title"><div><h3>{name}</h3><small>{detail}</small></div><span className="plate">{plate}</span></div>{active?<div className="vehicle-current"><Status stage="approval"/><b>Motorkontrollleuchte</b><small>Kostenvoranschlag liegt vor.</small></div>:<div className="vehicle-current neutral"><span>LETZTER SERVICE</span><b>Inspektion</b><small>17.06.2026</small></div>}</article>}

export function CustomerPortal({setView}:{setView:(v:AppView)=>void}){
 const [approved,setApproved]=useState(false); const [chat,setChat]=useState(false);
 return <Shell onHome={()=>setView('home')} title="Meine Garage" mode="Kundenportal" active="Fahrzeuge"><div className="page"><PageHead title="Meine Garage" subtitle="Deine Fahrzeuge, Aufträge und Dokumente an einem Ort."><div className="head-actions"><button className="btn secondary"><MapPin size={16}/> Werkstatt finden</button><button className="btn secondary" onClick={()=>setChat(true)}><MessageCircle size={16}/> Chat <span className="badge">1</span></button><button className="btn primary"><Plus size={16}/> Anfrage starten</button></div></PageHead><div className="customer-layout"><div className="garage"><VehicleCard name="BMW X3 3.0i" plate="SAD XX 123" detail="2005 · 247.318 km" active tone={0}/><VehicleCard name="VW Golf VII" plate="SAD VW 407" detail="2016 · 128.140 km" tone={1}/></div><section className="panel timeline"><div className="panel-title"><div><span className="overline">BMW X3 · AUFTRAG #184</span><h3>Aktueller Auftrag</h3></div><Status stage={approved?'repair':'approval'}/></div><Timeline title="Fahrzeug eingetroffen" detail="08:41 · Carplus Service Center"/><Timeline title="Diagnose abgeschlossen" detail="09:12 · Lambdasonde Bank 1 vor Kat"/><Timeline current title={approved?'Reparatur freigegeben':'Deine Freigabe ist erforderlich'} detail={approved?'09:31 · an Werkstatt übermittelt':'09:26 · Kostenvoranschlag bereitgestellt'}>{!approved&&<div className="quote"><div><small>KOSTENVORANSCHLAG · PDF</small><b>328,40 €</b><span>inkl. MwSt.</span></div><p>Lambdasonde Bank 1 vor Kat + Einbau</p><div><button className="btn primary" onClick={()=>setApproved(true)}>Reparatur freigeben</button><button className="btn secondary" onClick={()=>setChat(true)}>Rückfrage</button></div></div>}</Timeline><Timeline title="Reparatur" detail={approved?'Auftrag steht in der Werkstatt-Queue':'Startet nach Freigabe'}/><Timeline title="Abholbereit" detail="Noch nicht erreicht" last/></section></div></div><DemoChat open={chat} onClose={()=>setChat(false)} audience="customer"/></Shell>;
}

function Timeline({title,detail,current=false,last=false,children}:{title:string;detail:string;current?:boolean;last?:boolean;children?:React.ReactNode}){return <div className={`timeline-row ${current?'current':''} ${last?'last':''}`}><i/><div><b>{title}</b><small>{detail}</small>{children}</div></div>}

export function BrandingPage({setView}:{setView:(v:AppView)=>void}){
 const [url,setUrl]=useState<string>(); const [mode,setMode]=useState<'solo'|'team'>('solo');
 const logo=async(file?:File)=>{if(!file)return;const palette=await paletteFromLogo(file);applyPalette(palette);if(url)URL.revokeObjectURL(url);setUrl(URL.createObjectURL(file))};
 return <Shell onHome={()=>setView('home')} title="Carplus Service" mode="Werkstattprofil" active=""><div className="page"><PageHead title="Deine Werkstatt. Deine Identität." subtitle="MotorAtlas übernimmt die Wirkung deines Logos – aber nicht seine Lautstärke."><button className="btn primary">Änderungen speichern</button></PageHead><div className="branding-grid"><section className="panel"><span className="overline">ADAPTIVES BRANDING</span><h3>Logo rein. Premium-Farbsystem raus.</h3><p>MotorAtlas analysiert die dominante Markenfarbe und erzeugt daraus kontraststarke, dezente UI-Akzente.</p><label className="logo-upload"><Sparkles/><b>Werkstattlogo hochladen</b><span>PNG, JPG oder WebP</span><input type="file" accept="image/*" onChange={e=>logo(e.target.files?.[0])}/></label><div className="swatches"><i/><i/><i/></div></section><section className="panel preview"><span className="overline">LIVE-VORSCHAU</span><div className="profile-preview"><div className="preview-logo">{url?<img src={url} alt="Werkstattlogo"/>:<span>CS</span>}</div><div><b>Carplus Service Center</b><small><ShieldCheck size={14}/> Verifizierte Werkstatt</small></div></div><div className="preview-order"><Status stage="repair"/><h3>BMW X3 3.0i</h3><small>Auftrag #184 · Reparatur freigegeben</small><button className="btn primary full">Auftrag öffnen</button></div></section></div><section className="panel org-mode"><span className="overline">ORGANISATION</span><h3>Die Oberfläche passt sich an deinen Betrieb an.</h3><div><button className={mode==='solo'?'selected':''} onClick={()=>setMode('solo')}><Building2/><b>Einzelbetrieb</b><span>Eine Person sieht Büro und Werkstatt in einem flüssigen Ablauf.</span></button><button className={mode==='team'?'selected':''} onClick={()=>setMode('team')}><Users/><b>Team-Betrieb</b><span>Büro, Mechaniker und individuelle Berechtigungen arbeiten synchron.</span></button></div></section></div></Shell>;
}
